# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../01_deck.ipynb 2
from .card import *
from fastcore.utils import *

# %% ../01_deck.ipynb 4
class Deck:
    "A deck of 52 cards (no jokers)."
    def __init__(self): self.cards = [Card(s,r) for s in range(4) for r in range(1,14)]
    def __str__(self): return ' '.join(map(str, self.cards))
    def __len__(self): return len(self.cards)
    def __contains__(self, card): return card in self.cards
    __repr__ = __str__

# %% ../01_deck.ipynb 9
@patch
def pop(self:Deck,
        idx:int=-1): # The index of the card to remove (defaults to the last one)
    "Remove one card from the deck."
    return self.cards.pop(idx)

# %% ../01_deck.ipynb 12
@patch
def remove(self:Deck,
           card:Card): # The index of the card to remove (defaults to the last one)
    "Remove `card` from the deck or raise an exception if it isn't there."
    self.cards.remove(card)
